version: '3.3'

services:
  redis:
    image: redis:alpine
    restart: always
    hostname: redis
    ports:
      - "6379:6379"

  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blogApp
      MYSQL_USER: admin
      MYSQL_PASSWORD: password

  blogapp:
    build: .
    ports:
      - "8080:8080"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/blogApp
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      WAIT_HOST: db:3306
    depends_on:
      - db
      - redis